# Kubecost Helm chart values for production environment

# Adjust resource requests/limits for production
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Production-specific retention settings
prometheus:
  server:
    retention: 30d

# Enhanced persistence for production
persistentVolume:
  size: 100Gi

# Enable alerting in production
alertConfigs:
  enabled: true
