apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
  namespace: argo-workflows
type: Opaque
data:
  username: YXJnbw==  # "argo" in base64
  password: YXJnb3Bhc3N3b3Jk  # "argopassword" in base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: argo-workflows
  labels:
    app: postgres
data:
  POSTGRES_DB: argo_workflows
  POSTGRES_USER: argo
  POSTGRES_PASSWORD: argopassword
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: argo-workflows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: argo-workflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: argo-workflows
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
