{{- if .Values.nodePool.enabled }}
# NodePool defines how Karpenter should provision and manage nodes
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePool.name }}
spec:
  # Template defines the configuration for nodes that Karpenter will provision
  template:
    spec:
      # Requirements specify constraints for node provisioning
      requirements:
        # Architecture requirements
        - key: kubernetes.io/arch
          operator: In
          values: {{ .Values.nodePool.requirements.arch | toJson }}

        # OS requirements
        - key: kubernetes.io/os
          operator: In
          values: {{ .Values.nodePool.requirements.os | toJson }}

        # Capacity type requirements (spot/on-demand)
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .Values.nodePool.requirements.capacityType | toJson }}

        # Instance family requirements
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: {{ .Values.nodePool.requirements.instanceFamily | toJson }}

        # Instance size requirements
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: {{ .Values.nodePool.requirements.instanceSize | toJson }}

      # Reference to the EC2NodeClass
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodeClass.name }}

      # Node expiration configuration
      expireAfter: {{ .Values.nodePool.expireAfter }}

  # Maximum CPU cores allowed across all nodes in this pool
  limits:
    cpu: {{ .Values.nodePool.limits.cpu }}

  # Node consolidation and disruption settings
  disruption:
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter }}
    budgets:
      {{- range .Values.nodePool.disruption.budgets }}
      - nodes: {{ .nodes | quote }}
        schedule: {{ .schedule | quote }}
        duration: {{ .duration | quote }}
      {{- end }}
{{- end }}
