apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodeclass.yaml
  - nodepool.yaml

# Configure variable substitution
replacements:
  - source:
      kind: ConfigMap
      name: cluster-info
      fieldPath: data.clusterName
    targets:
      - select:
          kind: EC2NodeClass
        fieldPaths:
          - spec.role
          - spec.subnetSelectorTerms[0].tags.karpenter\.sh/discovery
          - spec.securityGroupSelectorTerms[0].tags.karpenter\.sh/discovery
        options:
          create: true

# Create a ConfigMap with cluster info
configMapGenerator:
  - name: cluster-info
    literals:
      - clusterName=${CLUSTER_NAME}
