apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: folder-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:abhishek-kundalia/gitops-bridge
      revision: HEAD
      directories:
      - path: eks-app-workloads/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:abhishek-kundalia/gitops-bridge
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true