apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: folder-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
      mergeKeys: [server]
      generators:
        - git:
            repoURL: git@github.com:abhishek-kundalia/gitops-bridge
            revision: HEAD
            directories:
            - path: eks-app-workloads/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: '{{.metadata.annotations.workload_repo_url}}'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true