{{- if .Values.externalSecret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-target
  namespace: {{ .Values.externalSecret.targetNamespace }}
  labels:
    {{- include "external-secrets-resources.labels" . | nindent 4 }}
    {{- with .Values.externalSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.externalSecret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecret.secret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secret.k8sSecretName }}
    creationPolicy: Owner
    template:
      type: {{ .Values.externalSecret.secret.secretType }}
  {{- if .Values.externalSecret.secret.dataMapping }}
  data:
  {{- range $k8sKey, $awsKey := .Values.externalSecret.secret.dataMapping }}
  - secretKey: {{ $k8sKey }}
    remoteRef:
      key: {{ $.Values.externalSecret.secret.awsSecretName }}
      property: {{ $awsKey }}
  {{- end }}
  {{- else }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.secret.awsSecretName }}
  {{- end }}
{{- end }}
